jobs:

  - job: Windows
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH

      - powershell: conda init cmd.exe
        displayName: Initiate conda support for cmd.exe
      
      - script: conda env create --file ./.azure/env.yml
        displayName: Create Anaconda environment

      - script: |
          conda activate irisbuild
          python -m unittest discover --verbose
        displayName: Unit tests 
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

  - job: Linux 
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      
      - bash: conda init bash
        displayName: Initiate conda support for bash
      
      - script: conda env create --file ./.azure/env.yml
        displayName: Create Anaconda environment

      - script: |
          conda activate irisbuild
          python -m unittest discover --verbose
        displayName: Unit tests 
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'