# Azure Pipelines support for anaconda is described here:
#   https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/anaconda?view=azure-devops&tabs=vs2017

jobs:

  # ------------------------------------------------------------
  #                 WINDOWS BUILD
  # ------------------------------------------------------------
  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH
      
      - script: conda env create --quiet --file ./.azure/env.yml
        displayName: Create Anaconda environment

      - bash: |
          source activate irisbuild
          python -Wa -m unittest discover --verbose
        displayName: Unit tests 
      
      - bash: |
          source activate irisbuild
          cd installer
          python -O -m PyInstaller --clean -y --distpath=dist\executable --onedir iris-onedir.spec
        displayName: Build executable with PyInstaller
      
      # # Command-line parameters for Inno Setup are specified here:
      # #   http://www.jrsoftware.org/ishelp/index.php?topic=compilercmdline
      # - bash: |
      #     source activate irisbuild
      #     VERSION=$(python -m iris --version)
      #     cd installer
      #     iscc iris-setup.iss
      #   displayName: Build Windows installer with ISCC 

      # # As of right now, only save Windows build artifacts
      # # because that's the only machine I have available to test them.
      # - task: PublishPipelineArtifact@0
      #   displayName: Publish artifacts
      #   inputs:
      #     artifactNames: setup$(pythonVersion)
      #     targetPath: installer/dist/setup/

    strategy:
      matrix:
        Python36:
          pythonVersion: '3.6'
        Python37:
          pythonVersion: '3.7'
        Python38:
          pythonVersion: '3.8'
        Python39:
          pythonVersion: '3.9'

  # ------------------------------------------------------------
  #                 LINUX BUILD
  # ------------------------------------------------------------
  - job: Linux 
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      
      - bash: conda env create --quiet --file ./.azure/env.yml
        displayName: Create Anaconda environment

      - bash: |
          source activate irisbuild
          python -Wa -m unittest discover --verbose
        displayName: Unit tests 

      - bash: |
          source activate irisbuild
          cd installer
          python -O -m PyInstaller --clean -y --distpath=dist\executable --onedir iris-onedir.spec
        displayName: Executable build
    strategy:
      matrix:
        Python36:
          pythonVersion: '3.6'
        Python37:
          pythonVersion: '3.7'
        Python38:
          pythonVersion: '3.8'
        Python39:
          pythonVersion: '3.9'
