jobs:

  - job: Windows
    pool:
      vmImage: 'VS2017-Win2016'
    steps:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH
      - template: ./.azure/steps.yml
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

  - job: Linux 
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH
      - template: ./.azure/steps.yml
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'